### ISSUE TITLE
Issue with pip installs and keras import

### ISSUE THREAD

**Issue by qbeer** [qati/DeepLearningCourse#2]
# Solved

 Hey, I had an issue with the first two cells in the HW notebook. I solved them by installing the packages in terminal with superuser privileges (with *sudo*). However, after that I kept getting the **ModuleNotFoundError: No module named 'keras'** for the *keras* import. I solved that by adding keras with conda, in terminal:

```bash
conda install keras
```

 This might be useful for other Ubuntu users.

**Comment by qati** [comment]
Hey,

Thanks for the comment.  I guess the problem was that you are using python 3 and installed the package with pip or you are using python-2 and installed the package with pip3. But yeah, if you are using anaconda then conda is the best and almost always working solution to install packages.
