### ISSUE TITLE
Final result of first homework

### ISSUE THREAD

**Issue by gerdos** [qati/DeepLearningCourse#4]
The final homework (nn_forward) has the following expected results:
[[0.49970579, 0.49971335], [0.50029421, 0.50028665]]
I am unable to replicate these results. The results i get are slightly off.
[[0.49967587 0.50032413], [0.49966831 0.50033169]].
Also for the first exercise of the second homework the entropy should be 0.6931397896985225 accourding to the results, however I get 0.6931549552268021. Can i get some hints about what am i missing?

**Comment by qati** [comment]
Hi,

please commit your solution so I can check it out.

**Comment by gerdos** [comment]
I did now, sorry.

**Comment by patbaa** [comment]
Hi,

That is an error (the expected output will be updated, probably that was an older version)! 
Your solution is correct, the grader gave maximum points.

Thanks for pointing it out.

**Comment by gerdos** [comment]
Thanks a lot, maybe check out 

losssoftmax_backward
linear_backward
nn_backward

As well, they seem slightly off as well!

Thanks again!
